// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hBcrR54ikIAxAL7gUI7v0BOHTIumKj4',
    appId: '1:212891163412:web:f5611f7a898671f0660001',
    messagingSenderId: '212891163412',
    projectId: 'localechat-32722',
    authDomain: 'localechat-32722.firebaseapp.com',
    storageBucket: 'localechat-32722.appspot.com',
    measurementId: 'G-6RLFJ1PC18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3UemTzNyD3XpSY3u2PQAEO5S9OiDbFDA',
    appId: '1:212891163412:android:156d7983d8a8c3e8660001',
    messagingSenderId: '212891163412',
    projectId: 'localechat-32722',
    storageBucket: 'localechat-32722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85Lin3EnfOnnBeLvkEVLFjcMItVXB2tc',
    appId: '1:212891163412:ios:bfa2bc0410860775660001',
    messagingSenderId: '212891163412',
    projectId: 'localechat-32722',
    storageBucket: 'localechat-32722.appspot.com',
    iosBundleId: 'com.example.localeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85Lin3EnfOnnBeLvkEVLFjcMItVXB2tc',
    appId: '1:212891163412:ios:88792ba73b089d6a660001',
    messagingSenderId: '212891163412',
    projectId: 'localechat-32722',
    storageBucket: 'localechat-32722.appspot.com',
    iosBundleId: 'com.example.localeChat.RunnerTests',
  );
}
